name: Jest Unit Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-Jest:
    name: Run Tests/Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn add --dev jest
    - run: yarn test
    - run: yarn coverage